version: '3.8'

services:
  grobid:
    image: grobid/grobid:0.8.0
    ports:
      - "8070:8070"
    restart: always

  app:
    build: .
    depends_on:
      - grobid
    volumes:
      - .:/app
    environment:
      - GROBID_SERVER=http://grobid:8070